# Generated by Django 5.2.6 on 2025-09-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/home')),
                ('price', models.IntegerField()),
                ('sity', models.TextField(blank=True, null=True)),
                ('location', models.TextField()),
            ],
        ),
    ]
