# Generated by Django 5.2.6 on 2025-09-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='type',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
