# Generated by Django 5.2.6 on 2025-09-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homa', '0002_home_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='baths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='beds',
            field=models.TextField(blank=True, null=True),
        ),
    ]
