# Generated by Django 5.2.6 on 2025-09-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homa', '0003_home_baths_home_beds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/customer')),
                ('reyting', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=120)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('job', models.CharField(max_length=120)),
            ],
        ),
    ]
